clean_source:
  1:
    type: Librispeech
    wav: \\ccpsofsep\am_s3\users\xioxiao\Data\Libri\train-clean-360.zip
    label: \\ccpsofsep\am_s3\users\xioxiao\Data\Libri\train-clean-460-pdf-ids.txt
#    aux_label: \\ccpsofsep\am_s3\users\xioxiao\Data\Libri\train-clean-460-word.txt
  2:
    type: Librispeech
    wav: \\ccpsofsep\am_s3\users\xioxiao\Data\Libri\train-clean-100.zip
    label: \\ccpsofsep\am_s3\users\xioxiao\Data\Libri\train-clean-460-pdf-ids.txt
#    aux_label: \\ccpsofsep\am_s3\users\xioxiao\Data\Libri\train-clean-100-word.txt
dir_noise:
  1:
    type: Noise
    wav: \\ccpsofsep\am_s3\users\xioxiao\Data\RIR_Noise\NoiseSegments_wav\NOISE.zip
rir:
  1:
    type: RIR
    wav: \\ccpsofsep\am_s3\users\xioxiao\Data\RIR_Noise\RIR\rir_c1_n10_t60_0.2_0.5_2018-08-07.zip
