clean_source:
  1:
    type: Librispeech
    wav: \\ccpsofsep\am_s3\users\chanliu\exp_data\data_libri_orig_nofs_no_shift\hdf5_data\data.hdf5
    label: \\ccpsofsep\am_s3\users\xioxiao\Data\Libri\train-clean-460-pdf-ids.txt
dir_noise:
  1:
    type: Noise
    wav: \\ccpsofsep\am_s3\users\xioxiao\Data\RIR_Noise\NoiseSegments_wav\NOISE.zip
rir:
  1:
    type: RIR
    wav: \\ccpsofsep\am_s3\users\xioxiao\Data\RIR_Noise\RIR\rir_c1_n10_t60_0.2_0.5_2018-08-07.zip
