clean_source:
  1:
    type: Librispeech
    wav: Path-to\train-clean-360.zip #or train-clean-360.hdf5
    label: Path-to\train-clean-460-pdf-ids.txt
#    aux_label: Path-to\train-clean-460-trans-ids.txt
  2:
    type: Librispeech
    wav: Path-to\train-clean-100.zip
    label: Path-to\train-clean-460-pdf-ids.txt
#    aux_label: Path-to\train-clean-100-trans-ids.txt
dir_noise:
  1:
    type: Noise
    wav: Path-to\noise.zip
rir:
  1:
    type: RIR
    wav: Path-to\rir.zip
